name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure the Node.js version matches the project's requirement

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL=$HOME/.bun
          export PATH=$BUN_INSTALL/bin:$PATH
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "PATH=$BUN_INSTALL/bin:$PATH" >> $GITHUB_ENV

      - name: Install packages
        run: bun install

      - name: Run Bun start
        run: bun start

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets
