name: Export Packed Data

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        id: set-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Distribution of Java (e.g., temurin, zulu, adopt, etc.)
          java-version: '17'        # Specify the Java version you need

      - name: Set up cache for Bun and Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Export Packed Data
        run: bun --bun run src/index.ts @dynamodb-export-packed-data

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets
