name: Generate packed data

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Create tables
        run: bun run bun:db-seed

      - name: Generate packed data
        run: bun run bun:db-export-packed-data

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets
