name: Test

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        id: set-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Distribution of Java (e.g., temurin, zulu, adopt, etc.)
          java-version: '17'        # Specify the Java version you need

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test
        run: npm run node:test
